### ISSUE TITLE
Missing License?

### ISSUE THREAD

**Issue by appden** [solidjs/solid-playground#112]
I was considering forking this playground to build an unrelated playground for a toy project, but I noticed this repo was missing a license. While it's easy to assume it would be MIT like the other Solid things, I can't presume to use any of this code without an explicit license. Thanks!

**Comment by modderme123** [comment]
I'm currently checking in with the team, but I think you should be safe assuming MIT, will add a license soon

**Comment by appden** [comment]
Thanks so much for quickly addressing this @modderme123!
