### ISSUE TITLE
Include third parties library imports in exported package.json

### ISSUE THREAD

**Issue by AyloSrd** [solidjs/solid-playground#113]
Currently, when we download (or export to CodeSandbox) a SolidJS Playground project that imports third parties packages, the generated JSON file does not include the imported packages in the dependencies list.

For instance, when I export [this small project](https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9msOABsAwlDJxeAX14AzRrRi8A5CNoATSQAtVAHQgcuPfr0ZwImuI1kKlK-TVoi0mgLQArMgHoA7nAARk4A3IbG3HwCzBZQuHAAymgA5tAidorKvE50rh7eoYaG8vQQzLhotBC8EvDikjYAFACU-Ia8glVkfMBCdRJSmgBywli8Uri1ogNww8IAurwAvIKx8UmpUCKNqqrNYdWdEN28wPEUuGMTACpwF4srMXBxiSlpO3vtCqXlldU6UCsIjgAEkIIR6LhGnBmoheAA3WhuNqHDo3O5QuAAOlwUEYyTguCx8K29BhXzRhKm9UGI3gjT60wa0JxeIJRJJIjJzWaXxkRUOFlwTGqjQpvAAPAA+cUdCUiKCBURSsFSUz4Bi2aDwXiAzTjEXCRCyjqSwK2Hwy1GmuXm3iWk1yjAQ3CO01VMEupYgAFA0HgyH8602jqcsne85Q5pBkOmh3ByU+BVKkRW2MSwhSgCamt42ukGEEwnSQikvDQZF4iAlPkzJozUol3SUEGSUpAjJpszpcBaMhrzaqbZrdetNbTvH2hiDhgsViaLWWUsl1JmFqlY00tGY9HgECJ7IAosC97gAEL4EGaMVgKCEQhOZoAQinmBk8yAA), that includes lodash, the generated package.json is the following:

```js
{
  "scripts": {
    "start": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "solid-js": "1.4.1"
  },
  "devDependencies": {
    "vite": "^2.9.9",
    "vite-plugin-solid": "^2.2.6"
  }
}
```
while we would expect dependencies to be like so: 
```js
...
  "dependencies": {
    "solid-js": "1.4.1",
    "lodash": "^4.17.21"
  },
...
```
This isn't  a big problem in iself, as we can `npm install ` the missing deps when we download the project, or just add them on CodeSandbox. However it would improve the dev experience to have them already included in the package.json when exporting it.

I already managed to obtain the same result in [this project of mine](https://reactplayground.vercel.app/#N4IgggDhB0BWDOAPEAuEBLAthA9gJwBcACAJQFMBDAYwIBojgiBXeMgZQIoLKIF8iAZnhyYiAcjyUaYgDoA7LLkIMiVSVzIkcOYvyEjx6mgFoAJiID0VADboycgrLnyqOOfGKQIRALxEAFACUvgB8DPJEkapuHkQA2q5MDvSsBADCOEkEALq+zKwcGv4ADIHyEVGSBEx4cgEVUVEAPABGTAQEbkRuabZUANY+wEGhRKkZWf6JDkQA1EQAjIG8IQ2N68DTBLxrjU0WbR1uq3VRZXI7znKu7sQ3nOhyZHh55lRMmPYE0ADmZAQAUWsZE+DgAQgBPACSpn8Em0jnON1iwh0eTUlG4Wh0UzcDyeeHOqO+kjkpme-iaXiIFhCgRAvCAA), a React Playground (still in beta, it might be broken), by extracting the imported packages from the bundle imports metafile (I use *esbuild*, but there is a similar feature in *Rollup*) and either find the version in the import (in case the user has done someting like `import { camelCase } from 'lodash@4.17.21'`) or sending a request to **UNPKG** to get the last version (fallback being `'name-of-the-package': 'latest'`).

This would make the export creation slightly slower than it currently is, as we would have to wait for the responses from UNPKG, but still we are talking about milliseconds, and it would anyways be faster than adding the deps manually for the developer.

I would like to submit a PR to implement this feature.
Would it be ok for the maineiners of this repository, or would it be considered as an unnecessary modification?

**Comment by modderme123** [comment]
This sounds awesome, and I would love a PR. (note that it will be quite a bit of work to weave the communication from rollup in a way that doesn't bloat the api)

**Comment by AyloSrd** [comment]
There is no problem, thank you for taking the time to reply :)
I am planning on pushing the PR by the end of this week, so that I can show what I had in mind for the communication from rollup.

**Comment by AyloSrd** [comment]
I updated the branch to master, and I am having a problem with the new compiler worker.
babel-preset-solid is throwing :
```
/main.tsx: _assert is not a function
    at ImportInjector._applyDefaults (babel-preset-solid.js?v=86f140c7:15593:11)
```
Is it my machine, or there is a bug there ?

**Comment by modderme123** [comment]
Is it possible you haven't run `pnpm i` recently?
