### ISSUE TITLE
console.logging Sets doesn't show items

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid-playground#114]
`console.log(set)` where `set` is a `Set` object renders as `Set {  }`. Clicking on that `Set` object shows the methods on `Set`, but still doesn't show the values. By contrast, `Array`s render as `Array [ ...items... ]` (and can be further expanded).

Example playground: https://playground.solidjs.com/?hash=-1802735031&version=1.4.1

**Comment by modderme123** [comment]
Neat! This is an issue with eruda's internal library [luna](https://github.com/liriliri/luna/issues), specifically [this file](https://github.com/liriliri/luna/blob/master/src/console/Log.ts). Feel free to copy this comment there
