### ISSUE TITLE
Playground in tutorial is not loading

### ISSUE THREAD

**Issue by AOrazaev** [solidjs/solid-playground#137]
Hi, it is been down for few days for me.

Repro steps:
1) Go to some tutorial page: https://www.solidjs.com/tutorial/stores_context
2) Look at the playground

Expected result:
Playground is loaded and functional

Actual result:
Playground window shows "Loading the playground..." text, console has one error:
The requested module 'https://cdn.skypack.dev/solid-js/web' does not provide an export named 'createComponent'

![image](https://user-images.githubusercontent.com/1423970/229340838-5969efd6-05a8-4f43-999c-cec883fc06eb.png)

Not sure if this is correct repo to submit issue though... If it is not, please kindly redirect me to the correct one. Thanks!

**Comment by modderme123** [comment]
Closing as fixed (Ryan published a new version that skypack accepted, and hopefully soon we'll publish a new version with jspm instead of skypack)
