### ISSUE TITLE
Playground is stuck in loading state in Firefox

### ISSUE THREAD

**Issue by snnsnn** [solidjs/solid-playground#141]
Playground started to get stuck in loading state in Firefox both in regular windows and private windows.  There are no errors in console. You can see the screenshot below for console logs.

Firefox 112.0.1
https://playground.solidjs.com/anonymous/71fcb2fd-b4c2-42dd-9f4e-c3c5b219935e

![image](https://user-images.githubusercontent.com/16473630/233821729-e6618c4e-a8bc-4c96-9527-d1e3bedfe25a.png)

**Comment by modderme123** [comment]
Thanks for the report! This should be fixed now, although it might take a reload or two to clear the cache (for some reason Firefox wouldn't play well with setting a targetOrigin on postMessage)
