### ISSUE TITLE
[Question] Import local files

### ISSUE THREAD

**Issue by funny-family** [solidjs/solid-playground#146]
Let's imagine that I want to create a component library and use a `solid-playground` as an environment for visually testing my components. How can I import my local component or any file to the playground?

**Comment by modderme123** [comment]
This is an interesting use case! The playground builds and runs libraries in a slightly different way than rollup might, so depending on the turnaround time you want you might consider:

* publishing the package and importing in the playground
* building the package to dist locally and copying and pasting the esm bundled file
* adding the source files to solid playground

Alternatively, if Solid Playground is currently missing features that are necessary for local testing, an alternative might be to use storybook, stackblitz, or codesandbox

Solid Playground is designed to support being embedded in docs, and we have an example of this integration on [Solid Site](https://github.com/solidjs/solid-site/blob/main/src/components/ReplTab.tsx) (if this is your use case and you run into missing features, we'd love to make this easier)

**Comment by funny-family** [comment]
@modderme123, thanks for answer.
