### ISSUE TITLE
[BUG] Failed to resolve module specifier [URL]. Invalid relative url or base scheme isn't hierarchical.

### ISSUE THREAD

**Issue by bigmistqke** [solidjs/solid-playground#153]
I get the following error `Failed to resolve module specifier "./foobar". Invalid relative url or base scheme isn't hierarchical.` when doing the following pattern in the playground:

```tsx
// ./foobar.ts
export const foo = "foo"
export const bar = "bar"

// ./T.tsx
export * as T from "./foobar"

// ./main.ts
import { T } from "./T"
```

playground: https://playground.solidjs.com/anonymous/0c6331a8-c5c8-4374-a284-81cd1754e7ff

**Comment by modderme123** [comment]
Looks like file re-exports weren't being transformed. This should be fixed now

**Comment by bigmistqke** [comment]
awesome it works thanks man!
