### ISSUE TITLE
Console doesn't seem to scroll in all environments

### ISSUE THREAD

**Issue by mosheduminer** [solidjs/solid-playground#21]
The log console in the REPL scrolls as expected in the playground, but does not scroll on the website (tutorial), instead it overflows hidden offscreen.

**Comment by amoutonbrady** [comment]
That's weird. That being said, as stated in #22, this should be taken care of when I release the next version of  `solid-repl` which is now part of this repo.

**Comment by amoutonbrady** [comment]
This should be fixed now.
