### ISSUE TITLE
Repl doesn't always refresh properly

### ISSUE THREAD

**Issue by mosheduminer** [solidjs/solid-playground#22]
When writing code in the REPL/playground, it seems that the `result` panel is not always updated properly. In particular, when following [this tutorial](https://dev.solidjs.com/tutorial/introduction_effects), the effect never runs. Switching to the output tab, and then back to the result tab causes the repl to refresh, and the effect runs as expected. There is probably some issue with the repl refreshing, perhaps when it hits an error during an intermediate compilation phase.

A stopgap would be to provide a button to rerun the REPL. This would also be of general utility, in case someone wishes to reset the state in the REPL.

[Discord report/discussion](https://discord.com/channels/722131463138705510/722131463889223772/845208072288075776).

**Comment by amoutonbrady** [comment]
We've completely revamped the portability of the REPL with @modderme123.

This should allow the REPL on the website to be a real component instead of an iframe and should take care of that issue.

**Comment by mosheduminer** [comment]
Great 👍.

**Comment by amoutonbrady** [comment]
This should be fixed now.
