### ISSUE TITLE
Adding a (hacky) way to disable TS checking

### ISSUE THREAD

**Issue by amoutonbrady** [solidjs/solid-playground#29]
In order to make the playground as easy as possible for people to share bug repro, we early on made sure TSX was supported (although everything is stripped away via @babel/preset-typescript).

Later on we switched from codemirror to monaco editor which added real time feedback related to typescript.

The issue is, due to the fact we use a virtual file system, some types doesn't work properly and may come in as annoying. Unfortunately, as of today there's no way to disable that at the monaco editor level.

That being said, adding a `// @ts-nocheck` at the top of the file do exactly that. Types still work as intended but they do not yell an error if there's some missing types.

I'd like to see a button to toggle that comment automatically while we look for a better solution.

**Comment by modderme123** [comment]
Ideally, we could set up a system that autoloads and caches types and sources for all files that would allow for offline compilation and type support of skypack packages

**Comment by amoutonbrady** [comment]
I would totally love that, unfortunately I technically really don't see how to do that as of today. I know you've mentioned a package that does that with unpkg but I don't think I'll be the one tackling that one unfortunately.

I do however fully agree on the fact that if we could have automatic types, it would be A-MAZ-ING.

**Comment by modderme123** [comment]
I got it working, should be able to mess with it here: https://github.com/modderme123/solid-playground/commit/877d45c009d56f40fedc2fe56fca15d98fa943eb

pnpm can sometimes be a bit finicky about the patched monaco version (make sure you only have 0.26.1)

**Comment by amoutonbrady** [comment]
Oh my god that cleans up so much of the codebase as well! [That package](https://www.npmjs.com/package/monaco-editor-auto-typings) looks really promising. Thank you for investigating that!

**Comment by edemaine** [comment]
FWIW, the original issue here has been solved recently (yay!). I'm not sure whether the later comments have been incorporated already or deserve keeping this issue open.

**Comment by davedbase** [comment]
Someone can revisit this in case it's a concern. Closing for now.
