### ISSUE TITLE
Adding a refresh button

### ISSUE THREAD

**Issue by amoutonbrady** [solidjs/solid-playground#33]
I'd love to have a refresh button above the preview pane which would essentially refresh the iframe and clear the console.

**Comment by nishit-prasad** [comment]
Hello! I am new and would like to contribute. Can I take this up if it's open to?

**Comment by modderme123** [comment]
Sure! Send us a message on discord if you run into trouble

**Comment by nishit-prasad** [comment]
Thank you! Appreciate it!

**Comment by nishit-prasad** [comment]
Thanks! Can I get the discord link please?

Further update: I have added the icon (shown in the below screenshot). Before going further with my implementation, is the below design good to go with?
<img width="864" alt="Screen Shot 2021-07-05 at 7 21 59 PM" src="https://user-images.githubusercontent.com/64563418/124481880-62748a80-ddc6-11eb-8e54-d4cea102ac40.png">

**Comment by modderme123** [comment]
Discord: https://discord.com/invite/solidjs

Is it possible to add it somewhere in the result/output tab so that it can be used in places like the tutorial (https://www.solidjs.com/tutorial/introduction_basics)?

**Comment by amoutonbrady** [comment]
I agree with @modderme123. The goal is to make the user understand that it reloads the iframe. The icon is looking good though!

**Comment by nishit-prasad** [comment]
Thank you guys! Let me redesign it and try to place the icon around there and will share my proposed design in the discord channel.

**Comment by amoutonbrady** [comment]
Hey, I took some of the discussion we wer4e talking about on Discord and went ahead with a first implementation. Feel free to improve upon it :)

Thanks again for your work 🙏🏻
