### ISSUE TITLE
Less hacky output pane

### ISSUE THREAD

**Issue by modderme123** [solidjs/solid-playground#34]
Right now the output is the file that is generated by rollup (with the imports having been changed to skypack and then back to regular imports). Instead, we might consider taking inspiration from the svelte repl and showing the babel compiled version of the currently active tab or actually displaying the skypack imports so that we can show the actual code that is run.

**Comment by amoutonbrady** [comment]
I'm not sure I quite picture what you are suggesting. Skipping the step where we replace the skypack imports and keeping track of the babel output for each tab and only showing that output instead of the rollup one?
