### ISSUE TITLE
Flexible Option To Export Either As Json file or Project Structured files(.zip optional) and vice versa for imports.

### ISSUE THREAD

**Issue by swise0** [solidjs/solid-playground#38]
If Possible, after running code in the playground, users should be given the export(download) button and be given the flexibility to choose whether they prefer their code in json format or a zip file containing the project's structured file and dependencies (in package.json file). This is  installed easily with npm install..

Eg. After downloading the zip format of the code. Within the zip file should contain a similar project file/folder structure:

./node_modules
./public/
           |
            -favicon.ico
            -index.html
            -bundle.css
            -index.js
./src/
        |
         -App.jsx
./package.json
./Readme.md

etc

**Comment by amoutonbrady** [comment]
Given the project is 99.9% client side rendered, with no backend I'm not sure how realistically that would possible.

**Comment by swise0** [comment]
> Given the project is 99.9% client side rendered, with no backend I'm not sure how realistically that would possible.

The svelte repl achieves a similar result.. if you do mind to check it out on how it organizes the code into a project structure after export..

**Comment by amoutonbrady** [comment]
Interesting. If I have a moment, I'll take a look.

That being said, I'm pretty sure they used sapper which has a server behind it and therefore they can have a zip export. We don't really beside cd workers.
