### ISSUE TITLE
Dark mode should apply to the Result too

### ISSUE THREAD

**Issue by trivikr** [solidjs/solid-playground#55]
## Describe the bug
The dark mode does not apply to result.

## Steps to reproduce
Solid Playground link: https://playground.solidjs.com/?hash=-596780144&version=1.1.0

#### Observed behavior
The dark mode is not applied to Result.

<details>
<summary>Screenshot: Light mode</summary>

<img width="896" alt="light-mode" src="https://user-images.githubusercontent.com/16024985/129840522-07cc78f2-eab9-4173-b7cb-362df03df08f.png">

</details>

<details>
<summary>Screenshot: Dark mode</summary>

<img width="896" alt="dark-mode" src="https://user-images.githubusercontent.com/16024985/129840532-296f085f-fe3c-40fd-9b7f-e33adbaa4951.png">

</details>

#### Expected behavior
Dark mode should apply to contents in the result too.

## Additional context
First pointed out in Discord https://discord.com/channels/722131463138705510/722167449251741798/874957933346193469

**Comment by swise0** [comment]
Issue still hasn't been fixed 🙂🤔
