### ISSUE TITLE
Should there be a central store for playground?

### ISSUE THREAD

**Issue by trivikr** [solidjs/solid-playground#58]
### Is your feature request related to a problem? Please describe.

While working on the dark mode in the following PRs, I noticed that lot of props are passed around.
* https://github.com/solidjs/solid-playground/pull/54
* https://github.com/solidjs/solid-playground/pull/56

Should there be a central store for these signals, so that they're not required to be passed between components?
PR for an attempt to create a store for dark signal in https://github.com/solidjs/solid-playground/pull/57

### Describe the solution you'd like
A better project structure where all TypeScript code is under src folder, and there's a central store from which values can be read.

### Describe alternatives you've considered
Keep passing values of signals between components as props.

**Comment by modderme123** [comment]
Closing as I introduce a central store in https://github.com/solidjs/solid-playground/pull/107
