### ISSUE TITLE
Suggestion: Add "Feedback / Submit new issue" button on top bar

### ISSUE THREAD

**Issue by paritosh149** [solidjs/solid-playground#61]

**Comment by edemaine** [comment]
I think a simple link to the solid-playground repo would probably suffice. The repo README can have all the necessary links (Issues for bug reports, link to Solid).

I feel like the GitHub mark <img height="25" src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"> would be the most natural icon for this.  I see two alternatives:

1. If we stick to [solid-heroicons](https://github.com/amoutonbrady/solid-heroicons), we could use the `information-circle` icon:

   ![image](https://user-images.githubusercontent.com/2218736/167650536-c50f7f59-263a-4ab2-8a36-65f29462178c.png)

2. If we switch to [solid-icons](https://github.com/x64Bits/solid-icons), we can use [another icon library that provides the GitHub mark](https://solid-icons-web.vercel.app/search/github):

   ![image](https://user-images.githubusercontent.com/2218736/167651261-14ccb071-921c-489a-9757-67acf91e51ef.png)


If I can get a vote on the preferred approach, I can work on a PR.

**Comment by ArindamPal-0** [comment]
If nobody is working on it, then you can check the pull request I made #143
