### ISSUE TITLE
Updating to monaco 0.31+ seems to break the typings...

### ISSUE THREAD

**Issue by amoutonbrady** [solidjs/solid-playground#70]
I tried to update the `monaco-editor` dependency to the latest (0.31.1) but it seems to break the custom typings we setup in the [`setupSolid.tsx`](https://github.com/solidjs/solid-playground/blob/master/src/components/editor/setupSolid.ts#L36-L63) file.

I did check their [CHANGELOG.md](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0311-14122021) but couldn't really pin point.

If anyone is willing to investigate, I'd be more than grateful, this stuff is way beyond me.

(cc @modderme123)

**Comment by modderme123** [comment]
I believe we are running into https://github.com/microsoft/monaco-editor/issues/2841
