### ISSUE TITLE
Bottom header bar removed

### ISSUE THREAD

**Issue by aquaductape** [solidjs/solid-playground#80]
Bottom header bar got removed or not visible. It contained formatter icon, when clicking it formatted/prettied code. Also  I can't seem find it in the source code, did it get removed? I looked through all imports of solid-heroicons and only see icons that are found at top header and right panel.
 
<img width="816" alt="Screen Shot 2022-01-20 at 2 00 46 PM" src="https://user-images.githubusercontent.com/29286430/150429187-87ea6805-2ea7-48eb-9954-24e85ab1410e.png">

**Comment by modderme123** [comment]
Yes, instead you can right-click on the editor and click format document or f1>format doc

**Comment by aquaductape** [comment]
Okay good to know, recently Ryan had a stream showing solidjs and he was looking for the format button to formate his code. I'll let him know about this change
