### ISSUE TITLE
Reset/Solve button in Solidjs Tutorial cause issues with tab state

### ISSUE THREAD

**Issue by timotius02** [solidjs/solid-playground#89]
I was going through the tutorial and found this buggy interaction between the Reset/Solve button and Playground.  

![solid-tutorial (1)](https://user-images.githubusercontent.com/5110237/159160229-76000680-51ba-424d-96fa-069dd1b3d3fe.gif)

Investigated it in solidjs/solid-site but it seems like the issue might be the Playground itself. I wanted to poke around some more but was hoping for some direction of what would be causing this issue.

**Comment by edemaine** [comment]
I think this was already [raised and fixed in solid-site](https://github.com/solidjs/solid-site/issues/273), so issue can be closed now. Let us know if you encounter it again!

**Comment by timotius02** [comment]
The same bug is still happening on the live site.
