### ISSUE TITLE
Issues when browsing through the examples on solid-js site

### ISSUE THREAD

**Issue by high1** [solidjs/solid-playground#98]
The issue can be observed when user picks one of the examples that have a css file included, switches to tab with CSS, and then picks another example which also has a css file in it. The tab changes to main.tsx for the second example, but in it are the contents of css file of that example.
![image](https://user-images.githubusercontent.com/783303/165653170-cd756935-7df0-4df2-825d-c033d2a55643.png)
![image](https://user-images.githubusercontent.com/783303/165653133-cf51531d-659a-4bd7-af51-fa12500e8366.png)

**Comment by modderme123** [comment]
I'm looking into this now. Thanks for the really clear reproduction!
